# Generated by Django 4.0 on 2021-12-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincart',
            options={'verbose_name': 'cart item'},
        ),
        migrations.AlterField(
            model_name='productincart',
            name='cart_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
